Name=input('Enter Your Name:')
Age=int(input('Enter Your Age:'))
Qualif=input('Enter Your Qualification:')
Year_Ex=int(input("Enter Your Years Of Experience:"))
print(Name,Age,Qualif,Year_Ex,sep='\n')
